### PR TITLE
Fix #27 issue, baseUrl from PSR7 server request

### LINKED ISSUE #27: Converted PSR7 request does not return correct baseUrl
This bug causes Zend Router to fail when used with Zend Expressive when the index is outside of the server root. The issue is that the scheme://host should not be part of Zend Request requestUri.

```php
//Zend\Request
$this->setRequestUri((string) $uri); //the scheme + host should be removed here
// $this->setRequestUri(preg_replace('#^[^/:]+://[^/]+#', '', $uri));
```

Test case

```php
use PHPUnit\Framework\TestCase;
use Zend\Diactoros\ServerRequestFactory;
use Zend\Http\PhpEnvironment\Request as ZendRequest;
use Zend\Psr7Bridge\Psr7ServerRequest;

class Bug extends TestCase
{
    public function test()
    {
        $_SERVER = [
            'HTTP_HOST' => 'host.com',
            'SERVER_PORT' => '80',
            'REQUEST_URI' => '/test/path/here/',
            'SCRIPT_FILENAME' => '/c/root/test/path/here/index.php',
            'PHP_SELF' => '/test/path/here/index.php',
            'SCRIPT_NAME' => '/test/path/here/index.php',
        ];

        $psr7 = ServerRequestFactory::fromGlobals();
        $converted = Psr7ServerRequest::toZend($psr7);
        $zend = new ZendRequest();

        $this->assertSame($zend->getBaseUrl(), $converted->getBaseUrl());
    }
```

```
PHPUnit 6.5.2 by Sebastian Bergmann and contributors.

F                                                                   1 / 1 (100%)

Time: 272 ms, Memory: 4.00MB

There was 1 failure:

1) Bug::test
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-'/test/path/here'
+''

tests\Bug.php:27
phpunit\phpunit\phpunit:53

FAILURES!
Tests: 1, Assertions: 1, Failures: 1.
```

### PR DESCRIPTION
**Pull request by ezimuel**
This PR fixes #27. It also fixes a couple of wrong behaviours in the previous tests using `getRequestUri()`. The `setRequestUri` for `Zend\Psr7Bridge\Zend\Request` needs to remove the `http(s)://hostname` from a URI. See the `Zend\Http\PhpEnvironment\Request` implementation [here](https://github.com/zendframework/zend-http/blob/master/src/PhpEnvironment/Request.php#L464).

### CODE REVIEW

File: src/Zend/Request.php [hunk 1]
```diff
@@ -43,7 +44,8 @@ public function __construct(
         $this->setAllowCustomMethods(true);
 
         $this->setMethod($method);
-        $this->setRequestUri((string) $uri);
+        // Remove the "http(s)://hostname" part from the URI
+        $this->setRequestUri(preg_replace('#^[^/:]+://[^/]+#', '', (string) $uri));
```
Comment (weierophinney) [inline src/Zend/Request.php:48]: Probably a better approach would be:

```php
$normalizedUri = $uri->getPath();
$normalizedUri .= $uri->getQuery() ? '?' . $uri->getQuery() : '';
$normalizedUri .= $uri->getFragment() ? '#' . $uri->getFragment() : '';
$this->setRequestUri($normalizedUri);
```

This will better ensure that if there is a missing scheme or the authority contains any unexpected characters, you will still have a URI that works correctly with zend-http.

**Review by weierophinney — DISMISSED** [review]

File: src/Zend/Request.php (hunk 1 above)
Comment (ezimuel) [reply src/Zend/Request.php:48]: We used the regular expression because it's already used in `Zend\Http\PhpEnvironment\Request` [see here](https://github.com/zendframework/zend-http/blob/master/src/PhpEnvironment/Request.php#L464).
Moreover, are you sure we need to include the fragment part?

Comment (weierophinney) [reply src/Zend/Request.php:48]: In the regex you provide above, the fragment will be included. If you want to omit it, my approach would make that simpler to accomplish.

Comment (ezimuel) [reply src/Zend/Request.php:48]: @weierophinney Your solution can be applied only if `$uri` is instanceof `Psr\Http\Message\UriInterface` but it can be also a string. I think the regexp is a more general solution here. What do you think?

Comment (weierophinney) [reply src/Zend/Request.php:48]: Ah, I was unaware that it could be a string; I assumed it was a `UriInterface` instance.

So... carry on!
