### PR TITLE
fixes #6 uploaded files bugs converting psr7 to zend-http

### LINKED ISSUE #6: does not convert uploaded files correctly
here: https://github.com/zendframework/zend-psr7bridge/blob/master/src/Psr7ServerRequest.php#L112

``` php
...
'tmp_name' => $upload->getStream()
...
```

this should be `string` not `StreamInterface` because of that zend-validator almost all file validators  does not work. Also:

``` php
// do request with 1 file
$files = $request->getUploadedFiles(); // returns array with 1 file
$request = Psr7ServerRequest::toZend($request);
$request2 = Psr7ServerRequest::fromZend($request);
$files2 = $request2->getUploadedFiles(); // return empty array
```

I understand that PSR7 does not have method in interface to retrieve `tmp_name` but maybe some kind of workaround could be used?

### PR DESCRIPTION
**Pull request by svycka**

### CODE REVIEW

File: test/Psr7ServerRequestTest.php [hunk 1]
```diff
@@ -247,19 +248,36 @@ public function getResponseData()
                         'test1' => [
                             'name' => 'test1.txt',
                             'type' => 'text/plain',
-                            'tmp_name' => '/tmp/phpXXX',
+                            'tmp_name' => __DIR__.'/Psr7ResponseTest.php',
```
Comment (svycka) [inline test/Psr7ServerRequestTest.php:251]: I had to change this because impossible to get stream metadata on not existing file

File: src/Psr7ServerRequest.php [hunk 2]
```diff
@@ -124,21 +124,18 @@ private static function convertUploadedFiles(array $uploadedFiles)
      */
     private static function convertFilesToUploaded(array $files)
     {
-        if (!isset($files['file'])) {
```
Comment (svycka) [inline src/Psr7ServerRequest.php:127]: Removed because I don't know why this is needed. maybe I am wrong here @weierophinney for what reason this is here?

File: test/Psr7ServerRequestTest.php [hunk 3]
```diff
@@ -296,12 +314,25 @@ public function testFromZend($uri, $method, $headers, $body, $query, $post, $fil
         // post
         $this->assertEquals($post, $psr7Request->getParsedBody());
         // files
-        foreach ($psr7Request->getUploadedFiles() as $name => $upload) {
```
Comment (svycka) [inline test/Psr7ServerRequestTest.php:299]: I had to change this because this was incorrect and buggy also I added test for uploading one file so this had to be changed.

**Comment by svycka** [comment]
ping @weierophinney

**Comment by MidnightDesign** [comment]
@weierophinney Can someone take a look at this? I've got problems with file uploads, and they're fixed when I use this patched version.

File: test/Psr7ServerRequestTest.php (hunk 1 above)
Comment (weierophinney) [inline test/Psr7ServerRequestTest.php:251]: This would be better done as `__FILE__`; I'll make that change on merge.

File: test/Psr7ServerRequestTest.php [hunk 4]
```diff
@@ -296,12 +314,25 @@ public function testFromZend($uri, $method, $headers, $body, $query, $post, $fil
...
+    }
+
+    private function compareUploadedFiles($zend, $psr7)
+    {
+        if (!$psr7 instanceof UploadedFileInterface) {
+            $this->assertEquals(count($zend), count($psr7), "number of files should be same");
+        }
+        foreach ($zend as $name => $value) {
+            if (is_array($value)) {
+                self::compareUploadedFiles($zend[$name], $psr7[$name]);
```
Comment (weierophinney) [inline test/Psr7ServerRequestTest.php:327]: This should be `$this->`, not `self::`; I'll update on merge.
